build site:
  image: node:latest
  stage: build
  script:
    - npm install --progress=false --legacy-peer-deps
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_HOSTINGER" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rave 'ssh -p 65002' --delete dist/ u593128525@195.35.49.150:/home/u593128525/public_html/
