build site:
  image: node:latest
  stage: build
  script:
    - npm install --progress=false --legacy-peer-deps
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_HOSTINGER" | ssh-add -
    - echo "Host *ntStrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - rsync -atve 'ssh -p 65002' dist/ u593128525@195.35.49.150:/home/u593128525/public_html/
