/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/matrs/glove.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export let gloveModelgroup = null;

const Glove_Model = ({ props }) => {
  gloveModelgroup = useRef();
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../public/matrs/glove.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={gloveModelgroup}
      {...props}
      dispose={null}
      scale={0.026}
      visible={false}
    >
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-0.301, 0, 0]}>
          <group name="d7e6873029d84de289b8313411e4bcb1abccleanermaterialmergergle">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4">
                  <group name="MorphMainGroup">
                    <mesh
                      name="Pads_low__BakeShape"
                      geometry={nodes.Pads_low__BakeShape.geometry}
                      material={materials["Material.001"]}
                      morphTargetDictionary={
                        nodes.Pads_low__BakeShape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Pads_low__BakeShape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_7">
                  <group name="MorphMainGroup001">
                    <mesh
                      name="Base_low__BakeShape"
                      geometry={nodes.Base_low__BakeShape.geometry}
                      material={materials["Material.002"]}
                      morphTargetDictionary={
                        nodes.Base_low__BakeShape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Base_low__BakeShape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Glove"
          position={[-4.03, 17.37, 5.49]}
          rotation={[-0.459, 0.564, 0.202]}
          scale={0.467}
        >
          <mesh
            name="Glove_1"
            geometry={nodes.Glove_1.geometry}
            material={materials["Farbe_-_Metallic_(Blau)"]}
          />
          <mesh
            name="Glove_2"
            geometry={nodes.Glove_2.geometry}
            material={materials["Aluminium_-_satiniert"]}
          />
          <mesh
            name="Glove_3"
            geometry={nodes.Glove_3.geometry}
            material={materials["Farbe_-_Emaille_glänzend_(Gelb)"]}
          />
          <mesh
            name="Glove_4"
            geometry={nodes.Glove_4.geometry}
            material={materials["Farbe_-_Emaille_glänzend_(Schwarz)"]}
          />
          <mesh
            name="Glove_5"
            geometry={nodes.Glove_5.geometry}
            material={materials["Aluminium_-_gebürstet,_radial"]}
          />
          <mesh
            name="Glove_6"
            geometry={nodes.Glove_6.geometry}
            material={materials["Stahl_-_satiniert"]}
          />
        </group>
      </group>
    </group>
  );
};

export default Glove_Model;
